Spelling: Turn on/off, Bluetooth
elementary/wingpanel-indicator-bluetooth pull request #149
Opened 2021-03-19 01:11 UTC by comradekingu

2021-03-19 10:04 UTC, jeremypw commented
Definitely an improvement but flagging for UX team for final sign off on text.

2021-03-19 11:19 UTC, comradekingu commented
@jeremypw Can I be on the UX team (other than signing off on my commits)?

2021-03-19 16:32 UTC, jeremypw commented
@comradekingu You need to contact @danrabbit I guess.

2021-03-19 17:16 UTC, danrabbit commented
@cassidyjames might have opinions about this. Even though "turn off" and "turn on" sound more like conversational English, I wonder if "disable" and "enable" are more visually distinct. I think so far the precedent has been to use "disable" and "enable"

2021-03-19 18:13 UTC, cassidyjames requested changes
Nice improvement, just a word order nitpick.

2021-03-19 18:13 UTC, cassidyjames commented on src/Widgets/DisplayWidget.vala
> +            context = _("Middle-click to turn off Bluetooth");
This is idiomatic, but sounds better to me in English, at least. And you can easily replace `Bluetooth` with a pronoun and it still reads correctly, i.e. `Turn it off`.

```suggestion
            context = _("Middle-click to turn Bluetooth off");
```

2021-03-19 18:13 UTC, cassidyjames commented on src/Widgets/DisplayWidget.vala
> +            context = _("Middle-click to turn on Bluetooth");
Same as above

```suggestion
            context = _("Middle-click to turn Bluetooth on");
```

2021-03-19 18:16 UTC, cassidyjames commented
@danrabbit ah I had loaded this tab before your comment and missed it. :) I'm mostly indifferent on "turn it off" vs "disable", though I do think turning off/on is how most people would say it. Enable/disable sounds more technical to me.

2021-03-19 19:07 UTC, comradekingu commented
I am more strongly for "turn on/off", seeing as it in this case it is actually on or off (no power), and not just enabled or disabled.
The distinction is if something can be disabled, but still have power, or also need to be enabled in addition to turning on. Only then, and if that also makes sense to point out I favour "enable/disable".

2021-03-20 02:15 UTC, cassidyjames approved these changes

2021-03-20 02:15 UTC, merged